# Compiler Configuration
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableIncrementalAnnotationProcessing=true
android.enableR8Incremental=true
android.enableR8.fullMode=true
android.r8.maxWorkers=4
android.r8.optimizedResourceShrinking=true
kotlin.code.style=official
# Project Configuration
project.name=REAREye
project.android.compileSdk=37
project.android.minSdk=36
project.android.targetSdk=37
project.android.buildToolsVersion=37.0.0
project.android.compileSdkMinor=0
project.app.packageName=hk.uwu.reareye
project.app.versionName="2.0.0"
project.app.versionCodename="Renovatio"
